# Generated by Django 3.2.14 on 2022-08-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='method_details',
            field=models.TextField(null=True),
        ),
    ]
