# Generated by Django 3.2.14 on 2022-08-01 18:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='approved',
        ),
        migrations.AlterField(
            model_name='tool',
            name='related_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='related_website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='time_required',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
