# Generated by Django 3.2.14 on 2022-08-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_alter_tool_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='time_required',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
