# Generated by Django 3.2.14 on 2022-08-10 07:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='time_required',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
