# Generated by Django 3.2.14 on 2022-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_alter_tool_time_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
