# Generated by Django 3.2.14 on 2022-08-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_alter_tool_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='method_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
