# Generated by Django 3.2.14 on 2022-08-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_tool_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='time_required',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
